Tejas_work
Gnsn-Alvero/Gnsn-Alvero pull request #8
Opened 2023-03-20 10:20 UTC by Tejas-Rote

Completed task Homepage - 06 
Implemented and also added Material UI library with custom theme.

2023-03-23 04:30 UTC, souravseal99 requested changes

2023-03-23 04:30 UTC, souravseal99 commented on src/App.js
> +// import homePage from "./componenets/HomePage/homePage";
if these are redundant comments, if so please remove them.

2023-03-23 04:30 UTC, souravseal99 commented on src/App.js
> +      {/* <nav class="main-nav">
try to remove all the redundant comments here too... just keep the essential comments.

2023-03-23 04:32 UTC, souravseal99 commented
hey @Tejas-Rote, I have resolved the merge conflict and requested some changes.

2023-03-26 15:38 UTC, Tejas-Rote commented on src/App.js
> +// import homePage from "./componenets/HomePage/homePage";
ok

2023-03-26 15:59 UTC, Tejas-Rote commented
please check .

2023-04-01 16:08 UTC, souravseal99 commented
any Updates @Tejas-Rote ?

2023-04-01 16:41 UTC, Tejas-Rote commented
I merged branch into main also removed the comments

2023-04-01 21:15 UTC, souravseal99 commented
> I merged branch into main also removed the comments

great🥇

2023-04-03 07:53 UTC, merged